"""Initial migration.

Revision ID: 06ba3e0541cb
Revises: 
Create Date: 2024-06-26 00:37:57.093327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ba3e0541cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('region',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('coordinates', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('pin', sa.String(length=4), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('civilization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('time_period', sa.String(length=100), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['region.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('civilization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['civilization_id'], ['civilization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('civilization_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['civilization_id'], ['civilization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saved_civs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('civilization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['civilization_id'], ['civilization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'civilization_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_civs')
    op.drop_table('event')
    op.drop_table('artifact')
    op.drop_table('civilization')
    op.drop_table('user')
    op.drop_table('region')
    # ### end Alembic commands ###
