"""Add Profile model

Revision ID: 6bfe09e49a5f
Revises: f11f0ea8be05
Create Date: 2024-06-26 13:05:18.075340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bfe09e49a5f'
down_revision = 'f11f0ea8be05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('knowledge', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('saved_civilizations', sa.String(length=255), nullable=True))
        batch_op.drop_column('bookmarks')
        batch_op.drop_column('civilizations')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('civilizations', sa.VARCHAR(length=255), nullable=True))
        batch_op.add_column(sa.Column('bookmarks', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('saved_civilizations')
        batch_op.drop_column('knowledge')

    # ### end Alembic commands ###
