"""Add pin_hash to User model

Revision ID: f11f0ea8be05
Revises: 0dd749ef7fa3
Create Date: 2024-06-26 12:40:34.252373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f11f0ea8be05'
down_revision = '0dd749ef7fa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pin_hash', sa.String(length=128), nullable=False))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.drop_column('profile_image')
        batch_op.drop_column('interests')
        batch_op.drop_column('pin')
        batch_op.drop_column('wants_to_know_more')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wants_to_know_more', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('pin', sa.VARCHAR(length=4), nullable=False))
        batch_op.add_column(sa.Column('interests', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('profile_image', sa.VARCHAR(length=200), nullable=True))
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('pin_hash')

    # ### end Alembic commands ###
